package org.crsystems.crbooks.ui.layouts;

import org.crsystems.crbooks.application.CRBooks;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class ApplicationLayout extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8661744972380461255L;
	
	
	private VerticalLayout mainLayout;
	private Panel panelMain;
	private VerticalLayout gridContent;
	private HorizontalLayout gridMenus;
	private MenuBar menuToolbar;
	private MenuBar menuLogo;

	public ApplicationLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		makeMenuCommands();
	}

	
	public void makeMenuCommands() {
		menuToolbar.removeItems();
		if (CRBooks.clientSignedIn()) {
			makeClientMenuCommands();
		} else if (CRBooks.managerSignedIn()) {
			makeManagerMenuCommands();
		} else if (CRBooks.adminSignedIn()) {
			makeAdminMenuCommands();
		}
	}


	private void makeAdminMenuCommands() {
		// TODO Auto-generated method stub
		
	}


	private void makeManagerMenuCommands() {
		// TODO Auto-generated method stub
		
	}


	private void makeClientMenuCommands() {
		// TODO Auto-generated method stub
		
	}


	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// gridMenus
		gridMenus = buildGridMenus();
		mainLayout.addComponent(gridMenus);
		
		// panelMain
		panelMain = buildPanelMain();
		mainLayout.addComponent(panelMain);
		mainLayout.setExpandRatio(panelMain, 1.0f);
		
		return mainLayout;
	}

	
	private HorizontalLayout buildGridMenus() {
		// common part: create layout
		gridMenus = new HorizontalLayout();
		gridMenus.setImmediate(false);
		gridMenus.setWidth("100.0%");
		gridMenus.setHeight("-1px");
		gridMenus.setMargin(false);
		
		// menuLogo
		menuLogo = new MenuBar();
		menuLogo.setImmediate(false);
		menuLogo.setWidth("100.0%");
		menuLogo.setHeight("-1px");
		gridMenus.addComponent(menuLogo);
		gridMenus.setExpandRatio(menuLogo, 1.0f);
		
		// menuToolbar
		menuToolbar = new MenuBar();
		menuToolbar.setImmediate(false);
		menuToolbar.setWidth("-1px");
		menuToolbar.setHeight("-1px");
		gridMenus.addComponent(menuToolbar);
		
		return gridMenus;
	}

	
	private Panel buildPanelMain() {
		// common part: create layout
		panelMain = new Panel();
		panelMain.setImmediate(false);
		panelMain.setWidth("100.0%");
		panelMain.setHeight("100.0%");
		
		// gridContent
		gridContent = new VerticalLayout();
		gridContent.setImmediate(false);
		gridContent.setWidth("100.0%");
		gridContent.setHeight("100.0%");
		gridContent.setMargin(false);
		panelMain.setContent(gridContent);
		
		return panelMain;
	}

}
