package org.crsystems.crbooks.ui.windows;

import org.apache.catalina.Manager;
import org.crsystems.crbooks.application.CRBooks;
import org.crsystems.crbooks.ui.layouts.ManagerLayout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class ConsultaGerente extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button buttonConsulta;
	@AutoGenerated
	private GridLayout gridLayout_4;
	@AutoGenerated
	private TextField textFieldApellidoCliente;
	@AutoGenerated
	private Label labelApellidoCliente;
	@AutoGenerated
	private GridLayout gridLayout_3;
	@AutoGenerated
	private TextField textFieldNombreCliente;
	@AutoGenerated
	private Label labelNombreCliente;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private GridLayout gridLayout_2;
	@AutoGenerated
	private PopupDateField DateEnd;
	@AutoGenerated
	private Label labelHasta;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private PopupDateField DateInit;
	@AutoGenerated
	private Label labelDesde;
	@AutoGenerated
	private Label labelSubtitulo;
	@AutoGenerated
	private Label labelTitulo;

	

	

	public ConsultaGerente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		mainLayout.setComponentAlignment(panel_1, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("-1px");
		panel_1.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("<h2>Reallizar Cosulta de Pedidos<h2>");
		labelTitulo.setContentMode(3);
		verticalLayout_2.addComponent(labelTitulo);
		verticalLayout_2.setComponentAlignment(labelTitulo, new Alignment(20));
		
		// labelSubtitulo
		labelSubtitulo = new Label();
		labelSubtitulo.setImmediate(false);
		labelSubtitulo.setWidth("-1px");
		labelSubtitulo.setHeight("-1px");
		labelSubtitulo.setValue("Seleccione las Fechas:");
		verticalLayout_2.addComponent(labelSubtitulo);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_2.addComponent(gridLayout_1);
		
		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		verticalLayout_2.addComponent(gridLayout_2);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Complete los datos del cliente");
		verticalLayout_2.addComponent(label_2);
		
		// gridLayout_3
		gridLayout_3 = buildGridLayout_3();
		verticalLayout_2.addComponent(gridLayout_3);
		
		// gridLayout_4
		gridLayout_4 = buildGridLayout_4();
		verticalLayout_2.addComponent(gridLayout_4);
		
		// buttonConsulta
		buttonConsulta = new Button();
		buttonConsulta.setCaption("Cosultar");
		buttonConsulta.setImmediate(true);
		buttonConsulta.addListener(new ClickListener(){

			public void buttonClick(ClickEvent event) {
				onButtonClick(DateInit,DateEnd,textFieldNombreCliente.getValue().toString(),textFieldApellidoCliente.getValue().toString());
				//CRBooks.setView(new ViewOrderClients(DateInit,DateEnd,textFieldNombreCliente.getValue().toString(),textFieldApellidoCliente.getValue().toString()));
				
			}

			
			
		});
		buttonConsulta.setWidth("-1px");
		buttonConsulta.setHeight("-1px");
		verticalLayout_2.addComponent(buttonConsulta);
		verticalLayout_2.setComponentAlignment(buttonConsulta,
				new Alignment(48));
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("-1px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		
		// labelDesde
		labelDesde = new Label();
		labelDesde.setImmediate(false);
		labelDesde.setWidth("-1px");
		labelDesde.setHeight("-1px");
		labelDesde.setValue("Desde");
		gridLayout_1.addComponent(labelDesde, 0, 0);
		
		// DateInit
		DateInit = new PopupDateField();
		DateInit.setDateFormat("yyyy-MM-dd");
		DateInit.setImmediate(true);
		DateInit.setWidth("-1px");
		DateInit.setHeight("-1px");
		DateInit.setInvalidAllowed(false);
		gridLayout_1.addComponent(DateInit, 1, 0);
		
		return gridLayout_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("-1px");
		gridLayout_2.setHeight("-1px");
		gridLayout_2.setMargin(false);
		gridLayout_2.setSpacing(true);
		gridLayout_2.setColumns(2);
		
		// labelHasta
		labelHasta = new Label();
		labelHasta.setImmediate(false);
		labelHasta.setWidth("-1px");
		labelHasta.setHeight("-1px");
		labelHasta.setValue(" Hasta");
		gridLayout_2.addComponent(labelHasta, 0, 0);
		
		// DateEnd
		DateEnd = new PopupDateField();
		DateEnd.setImmediate(true);
		DateEnd.setDateFormat("yyyy-MM-dd");
		DateEnd.setWidth("-1px");
		DateEnd.setHeight("-1px");
		DateEnd.setInvalidAllowed(false);
		gridLayout_2.addComponent(DateEnd, 1, 0);
		
		return gridLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_3() {
		// common part: create layout
		gridLayout_3 = new GridLayout();
		gridLayout_3.setImmediate(false);
		gridLayout_3.setWidth("-1px");
		gridLayout_3.setHeight("-1px");
		gridLayout_3.setMargin(false);
		gridLayout_3.setSpacing(true);
		gridLayout_3.setColumns(2);
		
		// labelNombreCliente
		labelNombreCliente = new Label();
		labelNombreCliente.setImmediate(false);
		labelNombreCliente.setWidth("-1px");
		labelNombreCliente.setHeight("-1px");
		labelNombreCliente.setValue("Nombre");
		gridLayout_3.addComponent(labelNombreCliente, 0, 0);
		
		// textFieldNombreCliente
		textFieldNombreCliente = new TextField();
		textFieldNombreCliente.setImmediate(false);
		textFieldNombreCliente.setWidth("-1px");
		textFieldNombreCliente.setHeight("-1px");
		textFieldNombreCliente.setSecret(false);
		gridLayout_3.addComponent(textFieldNombreCliente, 1, 0);
		
		return gridLayout_3;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_4() {
		// common part: create layout
		gridLayout_4 = new GridLayout();
		gridLayout_4.setImmediate(false);
		gridLayout_4.setWidth("-1px");
		gridLayout_4.setHeight("-1px");
		gridLayout_4.setMargin(false);
		gridLayout_4.setSpacing(true);
		gridLayout_4.setColumns(2);
		
		// labelApellidoCliente
		labelApellidoCliente = new Label();
		labelApellidoCliente.setImmediate(false);
		labelApellidoCliente.setWidth("-1px");
		labelApellidoCliente.setHeight("-1px");
		labelApellidoCliente.setValue("Apellido");
		gridLayout_4.addComponent(labelApellidoCliente, 0, 0);
		
		// textFieldApellidoCliente
		textFieldApellidoCliente = new TextField();
		textFieldApellidoCliente.setImmediate(false);
		textFieldApellidoCliente.setWidth("-1px");
		textFieldApellidoCliente.setHeight("-1px");
		textFieldApellidoCliente.setSecret(false);
		gridLayout_4.addComponent(textFieldApellidoCliente, 1, 0);
		
		return gridLayout_4;
	}
	
	
	private void onButtonClick(PopupDateField dateInit,	PopupDateField dateEnd,String nombre, String apellido) {
		ManagerLayout.getCurrent().changeView(new ViewOrderClients(dateInit,DateEnd,nombre,apellido));
	
		
	}
	
	
}
