package org.crsystems.crbooks.ui.windows;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class ConsultaGerente extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button buttonConsultar;
	@AutoGenerated
	private HorizontalLayout GridhorizontalLayout_4;
	@AutoGenerated
	private TextField textFieldApellidoCliente;
	@AutoGenerated
	private Label labelApellidoCliente;
	@AutoGenerated
	private TextField textFieldNombreCliente;
	@AutoGenerated
	private Label labelNombreCliente;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private HorizontalLayout GridhorizontalLayout_1;
	@AutoGenerated
	private PopupDateField DateEnd;
	@AutoGenerated
	private Label labelHasta;
	@AutoGenerated
	private PopupDateField DateInit;
	@AutoGenerated
	private Label labelDesde;
	@AutoGenerated
	private Label labelSubtitulo;
	@AutoGenerated
	private Label labelTitulo;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ConsultaGerente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("Reallizar Cosulta de Pedidos");
		mainLayout.addComponent(labelTitulo);
		mainLayout.setComponentAlignment(labelTitulo, new Alignment(48));
		
		// labelSubtitulo
		labelSubtitulo = new Label();
		labelSubtitulo.setImmediate(false);
		labelSubtitulo.setWidth("-1px");
		labelSubtitulo.setHeight("-1px");
		labelSubtitulo.setValue("Seleccione las Fechas:");
		mainLayout.addComponent(labelSubtitulo);
		mainLayout.setComponentAlignment(labelSubtitulo, new Alignment(33));
		
		// GridhorizontalLayout_1
		GridhorizontalLayout_1 = buildGridhorizontalLayout_1();
		mainLayout.addComponent(GridhorizontalLayout_1);
		mainLayout.setComponentAlignment(GridhorizontalLayout_1, new Alignment(
				34));
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Complete los datos del cliente");
		mainLayout.addComponent(label_2);
		
		// GridhorizontalLayout_4
		GridhorizontalLayout_4 = buildGridhorizontalLayout_4();
		mainLayout.addComponent(GridhorizontalLayout_4);
		mainLayout.setComponentAlignment(GridhorizontalLayout_4, new Alignment(
				33));
		
		// buttonConsultar
		buttonConsultar = new Button();
		buttonConsultar.setCaption("Consultar");
		buttonConsultar.setImmediate(true);
		buttonConsultar.setWidth("-1px");
		buttonConsultar.setHeight("-1px");
		mainLayout.addComponent(buttonConsultar);
		mainLayout.setComponentAlignment(buttonConsultar, new Alignment(9));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildGridhorizontalLayout_1() {
		// common part: create layout
		GridhorizontalLayout_1 = new HorizontalLayout();
		GridhorizontalLayout_1.setImmediate(false);
		GridhorizontalLayout_1.setWidth("500px");
		GridhorizontalLayout_1.setHeight("-1px");
		GridhorizontalLayout_1.setMargin(false);
		GridhorizontalLayout_1.setSpacing(true);
		
		// labelDesde
		labelDesde = new Label();
		labelDesde.setImmediate(false);
		labelDesde.setWidth("-1px");
		labelDesde.setHeight("-1px");
		labelDesde.setValue("Desde:");
		GridhorizontalLayout_1.addComponent(labelDesde);
		
		// DateInit
		DateInit = new PopupDateField();
		DateInit.setImmediate(false);
		DateInit.setWidth("-1px");
		DateInit.setHeight("-1px");
		DateInit.setInvalidAllowed(false);
		GridhorizontalLayout_1.addComponent(DateInit);
		
		// labelHasta
		labelHasta = new Label();
		labelHasta.setImmediate(false);
		labelHasta.setWidth("-1px");
		labelHasta.setHeight("-1px");
		labelHasta.setValue("Hasta:");
		GridhorizontalLayout_1.addComponent(labelHasta);
		
		// DateEnd
		DateEnd = new PopupDateField();
		DateEnd.setImmediate(false);
		DateEnd.setWidth("-1px");
		DateEnd.setHeight("-1px");
		DateEnd.setInvalidAllowed(false);
		GridhorizontalLayout_1.addComponent(DateEnd);
		
		return GridhorizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildGridhorizontalLayout_4() {
		// common part: create layout
		GridhorizontalLayout_4 = new HorizontalLayout();
		GridhorizontalLayout_4.setImmediate(false);
		GridhorizontalLayout_4.setWidth("-1px");
		GridhorizontalLayout_4.setHeight("-1px");
		GridhorizontalLayout_4.setMargin(false);
		GridhorizontalLayout_4.setSpacing(true);
		
		// labelNombreCliente
		labelNombreCliente = new Label();
		labelNombreCliente.setImmediate(false);
		labelNombreCliente.setWidth("-1px");
		labelNombreCliente.setHeight("-1px");
		labelNombreCliente.setValue("Nombre:");
		GridhorizontalLayout_4.addComponent(labelNombreCliente);
		
		// textFieldNombreCliente
		textFieldNombreCliente = new TextField();
		textFieldNombreCliente.setImmediate(false);
		textFieldNombreCliente.setWidth("-1px");
		textFieldNombreCliente.setHeight("-1px");
		textFieldNombreCliente.setSecret(false);
		GridhorizontalLayout_4.addComponent(textFieldNombreCliente);
		
		// labelApellidoCliente
		labelApellidoCliente = new Label();
		labelApellidoCliente.setImmediate(false);
		labelApellidoCliente.setWidth("-1px");
		labelApellidoCliente.setHeight("-1px");
		labelApellidoCliente.setValue("Apellido:");
		GridhorizontalLayout_4.addComponent(labelApellidoCliente);
		
		// textFieldApellidoCliente
		textFieldApellidoCliente = new TextField();
		textFieldApellidoCliente.setImmediate(false);
		textFieldApellidoCliente.setWidth("-1px");
		textFieldApellidoCliente.setHeight("-1px");
		textFieldApellidoCliente.setSecret(false);
		GridhorizontalLayout_4.addComponent(textFieldApellidoCliente);
		
		return GridhorizontalLayout_4;
	}
	
	
}
