package org.crsystems.crbooks.ui.windows;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class EditBookWindow extends CustomComponent {

	
	private VerticalLayout mainLayout;
	private Panel panelForm;
	private VerticalLayout gridForm;
	private GridLayout gridFormParams;
	private Button buttonForm;
	private TextField textStock;
	private Label labelStock;
	private OptionGroup optionCategories;
	private Label labelCategories;
	private TextField textPrice;
	private Label labelPrice;
	private TextField textDescription;
	private Label labelDescription;
	private TextField textEdition;
	private Label labelEdition;
	private ComboBox comboPublisher;
	private Label labelPublisher;
	private ComboBox comboAuthor;
	private Label labelAuthor;
	private TextField textTitle;
	private Label labelTitle;
	private Label labelFormHeader;

	public EditBookWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// panelForm
		panelForm = buildPanelForm();
		mainLayout.addComponent(panelForm);
		mainLayout.setComponentAlignment(panelForm, new Alignment(48));
		
		return mainLayout;
	}

	
	private Panel buildPanelForm() {
		// common part: create layout
		panelForm = new Panel();
		panelForm.setImmediate(false);
		panelForm.setWidth("-1px");
		panelForm.setHeight("-1px");
		
		// gridForm
		gridForm = buildGridForm();
		panelForm.setContent(gridForm);
		
		return panelForm;
	}

	
	private VerticalLayout buildGridForm() {
		// common part: create layout
		gridForm = new VerticalLayout();
		gridForm.setImmediate(false);
		gridForm.setWidth("100.0%");
		gridForm.setHeight("100.0%");
		gridForm.setMargin(true);
		gridForm.setSpacing(true);
		
		// labelFormHeader
		labelFormHeader = new Label();
		labelFormHeader.setImmediate(false);
		labelFormHeader.setWidth("-1px");
		labelFormHeader.setHeight("-1px");
		labelFormHeader.setValue("<h2>Editar el nuevo libro</h2>");
		labelFormHeader.setContentMode(3);
		gridForm.addComponent(labelFormHeader);
		
		// gridFormParams
		gridFormParams = buildGridFormParams();
		gridForm.addComponent(gridFormParams);
		
		return gridForm;
	}

	
	private GridLayout buildGridFormParams() {
		// common part: create layout
		gridFormParams = new GridLayout();
		gridFormParams.setImmediate(false);
		gridFormParams.setWidth("-1px");
		gridFormParams.setHeight("100.0%");
		gridFormParams.setMargin(false);
		gridFormParams.setSpacing(true);
		gridFormParams.setColumns(2);
		gridFormParams.setRows(9);
		
		// labelTitle
		labelTitle = new Label();
		labelTitle.setImmediate(false);
		labelTitle.setWidth("-1px");
		labelTitle.setHeight("-1px");
		labelTitle.setValue("Título:");
		gridFormParams.addComponent(labelTitle, 0, 0);
		
		// textTitle
		textTitle = new TextField();
		textTitle.setImmediate(false);
		textTitle.setWidth("100.0%");
		textTitle.setHeight("-1px");
		textTitle.setSecret(false);
		gridFormParams.addComponent(textTitle, 1, 0);
		
		// labelAuthor
		labelAuthor = new Label();
		labelAuthor.setImmediate(false);
		labelAuthor.setWidth("-1px");
		labelAuthor.setHeight("-1px");
		labelAuthor.setValue("Autor:");
		gridFormParams.addComponent(labelAuthor, 0, 1);
		
		// comboAuthor
		comboAuthor = new ComboBox();
		comboAuthor.setImmediate(false);
		comboAuthor.setWidth("-1px");
		comboAuthor.setHeight("-1px");
		comboAuthor.setInvalidAllowed(false);
		comboAuthor.setWriteThrough(false);
		gridFormParams.addComponent(comboAuthor, 1, 1);
		
		// labelPublisher
		labelPublisher = new Label();
		labelPublisher.setImmediate(false);
		labelPublisher.setWidth("-1px");
		labelPublisher.setHeight("-1px");
		labelPublisher.setValue("Editorial:");
		gridFormParams.addComponent(labelPublisher, 0, 2);
		
		// comboPublisher
		comboPublisher = new ComboBox();
		comboPublisher.setImmediate(false);
		comboPublisher.setWidth("-1px");
		comboPublisher.setHeight("-1px");
		comboPublisher.setInvalidAllowed(false);
		comboPublisher.setWriteThrough(false);
		gridFormParams.addComponent(comboPublisher, 1, 2);
		
		// labelEdition
		labelEdition = new Label();
		labelEdition.setImmediate(false);
		labelEdition.setWidth("-1px");
		labelEdition.setHeight("-1px");
		labelEdition.setValue("Edición:");
		gridFormParams.addComponent(labelEdition, 0, 3);
		
		// textEdition
		textEdition = new TextField();
		textEdition.setImmediate(false);
		textEdition.setWidth("100.0%");
		textEdition.setHeight("-1px");
		textEdition.setSecret(false);
		gridFormParams.addComponent(textEdition, 1, 3);
		
		// labelDescription
		labelDescription = new Label();
		labelDescription.setImmediate(false);
		labelDescription.setWidth("-1px");
		labelDescription.setHeight("-1px");
		labelDescription.setValue("Descripción:");
		gridFormParams.addComponent(labelDescription, 0, 4);
		
		// textDescription
		textDescription = new TextField();
		textDescription.setImmediate(false);
		textDescription.setWidth("100.0%");
		textDescription.setHeight("-1px");
		textDescription.setSecret(false);
		gridFormParams.addComponent(textDescription, 1, 4);
		
		// labelPrice
		labelPrice = new Label();
		labelPrice.setImmediate(false);
		labelPrice.setWidth("-1px");
		labelPrice.setHeight("-1px");
		labelPrice.setValue("Precio:");
		gridFormParams.addComponent(labelPrice, 0, 5);
		
		// textPrice
		textPrice = new TextField();
		textPrice.setImmediate(false);
		textPrice.setWidth("100.0%");
		textPrice.setHeight("-1px");
		textPrice.setSecret(false);
		gridFormParams.addComponent(textPrice, 1, 5);
		
		// labelCategories
		labelCategories = new Label();
		labelCategories.setImmediate(false);
		labelCategories.setWidth("-1px");
		labelCategories.setHeight("-1px");
		labelCategories.setValue("Categorias:");
		gridFormParams.addComponent(labelCategories, 0, 6);
		
		// optionCategories
		optionCategories = new OptionGroup();
		optionCategories.setImmediate(false);
		optionCategories.setWidth("100.0%");
		optionCategories.setHeight("-1px");
		gridFormParams.addComponent(optionCategories, 1, 6);
		
		// labelStock
		labelStock = new Label();
		labelStock.setImmediate(false);
		labelStock.setWidth("-1px");
		labelStock.setHeight("-1px");
		labelStock.setValue("Cantidad en stock:");
		gridFormParams.addComponent(labelStock, 0, 7);
		
		// textStock
		textStock = new TextField();
		textStock.setImmediate(false);
		textStock.setWidth("100.0%");
		textStock.setHeight("-1px");
		textStock.setSecret(false);
		gridFormParams.addComponent(textStock, 1, 7);
		
		// buttonForm
		buttonForm = new Button();
		buttonForm.setCaption("Crear Libro");
		buttonForm.setImmediate(false);
		buttonForm.setWidth("-1px");
		buttonForm.setHeight("-1px");
		gridFormParams.addComponent(buttonForm, 1, 8);
		gridFormParams.setComponentAlignment(buttonForm, new Alignment(6));
		
		return gridFormParams;
	}

}
