package org.crsystems.crbooks.ui.windows;

import java.util.List;

import org.crsystems.crbooks.models.Book;
import org.crsystems.crbooks.ui.controls.BookMiniDetails;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class HomeWindow extends CustomComponent {

	
	private VerticalLayout mainLayout;
	private Panel panelBase;
	private VerticalLayout gridContent;
	private VerticalLayout gridLastBooks;
	private Label labelHeader;
	private Panel panelLastNew;
	private VerticalLayout gridLastView;
	private Label labelLastNew;

	public HomeWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		makeBookList();
		setLastNew();
	}

	
	private void setLastNew() {
		ThemeResource src = new ThemeResource("img/notice/notice1.png");
		Embedded e = new Embedded();
		e.setSource(src);
		e.setSizeFull();
		this.gridLastView.addComponent(e);
	}


	private void makeBookList() {
		List<Book> list = Book.getAll();
		for (Book book : (list.size() > 9) ? list.subList(list.size() - 10, list.size() - 1)  : list) {
			if (book == null) break;
			this.gridLastBooks.addComponent(new BookMiniDetails(book));
		}
	}


	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// panelBase
		panelBase = buildPanelBase();
		mainLayout.addComponent(panelBase);
		mainLayout.setExpandRatio(panelBase, 1.0f);
		mainLayout.setComponentAlignment(panelBase, new Alignment(48));
		
		return mainLayout;
	}

	
	private Panel buildPanelBase() {
		// common part: create layout
		panelBase = new Panel();
		panelBase.setImmediate(false);
		panelBase.setWidth("-1px");
		panelBase.setHeight("100.0%");
		
		// gridContent
		gridContent = buildGridContent();
		panelBase.setContent(gridContent);
		
		return panelBase;
	}

	
	private VerticalLayout buildGridContent() {
		// common part: create layout
		gridContent = new VerticalLayout();
		gridContent.setImmediate(false);
		gridContent.setWidth("-1px");
		gridContent.setHeight("-1px");
		gridContent.setMargin(true);
		gridContent.setSpacing(true);
		
		// labelLastNew
		labelLastNew = new Label();
		labelLastNew.setImmediate(false);
		labelLastNew.setWidth("-1px");
		labelLastNew.setHeight("-1px");
		labelLastNew.setValue("<h1>Última novedad</h1>");
		labelLastNew.setContentMode(3);
		gridContent.addComponent(labelLastNew);
		gridContent.setComponentAlignment(labelLastNew, new Alignment(20));
		
		// panelLastNew
		panelLastNew = buildPanelLastNew();
		gridContent.addComponent(panelLastNew);
		
		// labelHeader
		labelHeader = new Label();
		labelHeader.setImmediate(false);
		labelHeader.setWidth("-1px");
		labelHeader.setHeight("-1px");
		labelHeader.setValue("<h1>Últimos libros agregados</h1>");
		labelHeader.setContentMode(3);
		gridContent.addComponent(labelHeader);
		gridContent.setComponentAlignment(labelHeader, new Alignment(20));
		
		// gridLastBooks
		gridLastBooks = new VerticalLayout();
		gridLastBooks.setImmediate(false);
		gridLastBooks.setWidth("100%");
		gridLastBooks.setHeight("-1px");
		gridLastBooks.setMargin(false);
		gridContent.addComponent(gridLastBooks);
		gridContent.setComponentAlignment(gridLastBooks, new Alignment(20));
		
		return gridContent;
	}

	
	private Panel buildPanelLastNew() {
		// common part: create layout
		panelLastNew = new Panel();
		panelLastNew.setImmediate(false);
		panelLastNew.setWidth("480px");
		panelLastNew.setHeight("320px");
		
		// gridLastView
		gridLastView = new VerticalLayout();
		gridLastView.setImmediate(false);
		gridLastView.setWidth("100.0%");
		gridLastView.setHeight("100.0%");
		gridLastView.setMargin(false);
		panelLastNew.setContent(gridLastView);
		
		return panelLastNew;
	}

}
