package org.crsystems.crbooks.ui.windows;

import org.crsystems.crbooks.application.CRBooks;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class SearchBooksWindow extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_5;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private GridLayout gridLayout_3;
	@AutoGenerated
	private Button buttonSearch;
	@AutoGenerated
	private TextField textFieldLibro;
	@AutoGenerated
	private Label labelLibro;
	@AutoGenerated
	private TextField textFieldAutor;
	@AutoGenerated
	private Label labelAutor;
	@AutoGenerated
	private Label labelTittle1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public static String titulo;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchBooksWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_5
		panel_5 = buildPanel_5();
		mainLayout.addComponent(panel_5);
		mainLayout.setComponentAlignment(panel_5, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_5() {
		// common part: create layout
		panel_5 = new Panel();
		panel_5.setImmediate(false);
		panel_5.setWidth("-1px");
		panel_5.setHeight("-1px");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panel_5.setContent(verticalLayout_4);
		
		return panel_5;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("-1px");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(false);
		verticalLayout_4.setSpacing(true);
		
		// labelTittle1
		labelTittle1 = new Label();
		labelTittle1.setImmediate(false);
		labelTittle1.setWidth("-1px");
		labelTittle1.setHeight("-1px");
		labelTittle1.setValue("<h2>Busqueda de Libros<h2>");
		labelTittle1.setContentMode(3);
		verticalLayout_4.addComponent(labelTittle1);
		verticalLayout_4.setComponentAlignment(labelTittle1, new Alignment(20));
		
		// gridLayout_3
		gridLayout_3 = buildGridLayout_3();
		verticalLayout_4.addComponent(gridLayout_3);
		verticalLayout_4.setComponentAlignment(gridLayout_3, new Alignment(20));
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_3() {
		// common part: create layout
		gridLayout_3 = new GridLayout();
		gridLayout_3.setImmediate(false);
		gridLayout_3.setWidth("-1px");
		gridLayout_3.setHeight("-1px");
		gridLayout_3.setMargin(true);
		gridLayout_3.setSpacing(true);
		gridLayout_3.setColumns(2);
		gridLayout_3.setRows(4);
		
		// labelAutor
		labelAutor = new Label();
		labelAutor.setImmediate(false);
		labelAutor.setWidth("-1px");
		labelAutor.setHeight("-1px");
		labelAutor.setValue("Por Autor");
		gridLayout_3.addComponent(labelAutor, 0, 0);
		
		// textFieldAutor
		textFieldAutor = new TextField();
		textFieldAutor.setImmediate(true);
		textFieldAutor.setWidth("-1px");
		textFieldAutor.setHeight("-1px");
		textFieldAutor.setSecret(false);
		gridLayout_3.addComponent(textFieldAutor, 1, 0);
		
		// labelLibro
		labelLibro = new Label();
		labelLibro.setImmediate(false);
		labelLibro.setWidth("-1px");
		labelLibro.setHeight("-1px");
		labelLibro.setValue("Por Libro");
		gridLayout_3.addComponent(labelLibro, 0, 1);
		
		// textFieldLibro
		textFieldLibro = new TextField();
		textFieldLibro.setImmediate(true);
		textFieldLibro.setWidth("-1px");
		textFieldLibro.setHeight("-1px");
		textFieldLibro.setSecret(false);
		gridLayout_3.addComponent(textFieldLibro, 1, 1);
		
		// buttonSearch
		buttonSearch = new Button();
		buttonSearch.setImmediate(true);
		buttonSearch.addListener(new ClickListener (){

			public void buttonClick(ClickEvent event) {
				CRBooks.setView(new ViewResultsSearchBooks());
				
			}
			
		});
		buttonSearch.setCaption("Buscar");		
		buttonSearch.setWidth("-1px");
		buttonSearch.setHeight("-1px");
		gridLayout_3.addComponent(buttonSearch, 1, 3);
		
		return gridLayout_3;
	}
	
	

}
