package org.crsystems.crbooks.ui.windows;

import org.crsystems.crbooks.application.CRBooks;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class ViewUserOrders extends CustomComponent {

	private VerticalLayout mainLayout;
	private Panel panelBase;
	private VerticalLayout gridBase;
	private Label labelHeader;

	public ViewUserOrders() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		if (CRBooks.getCurrentUser().getOrders() == null || CRBooks.getCurrentUser().getOrders().size() < 1) {
			drawNoOrdersPanel();
		} else {
			drawOrdersTable();
		}
	}

	
	private void drawOrdersTable() {
	}


	private void drawNoOrdersPanel() {
	}


	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panelBase
		panelBase = buildPanelBase();
		mainLayout.addComponent(panelBase);
		mainLayout.setExpandRatio(panelBase, 1.0f);
		
		return mainLayout;
	}

	
	private Panel buildPanelBase() {
		// common part: create layout
		panelBase = new Panel();
		panelBase.setImmediate(false);
		panelBase.setWidth("-1px");
		panelBase.setHeight("100.0%");
		
		// gridBase
		gridBase = buildGridBase();
		panelBase.setContent(gridBase);
		
		return panelBase;
	}

	
	private VerticalLayout buildGridBase() {
		// common part: create layout
		gridBase = new VerticalLayout();
		gridBase.setImmediate(false);
		gridBase.setWidth("100.0%");
		gridBase.setHeight("100.0%");
		gridBase.setMargin(true);
		
		// labelHeader
		labelHeader = new Label();
		labelHeader.setImmediate(false);
		labelHeader.setWidth("-1px");
		labelHeader.setHeight("-1px");
		labelHeader.setValue("<h3>Pedidos realizados</h3>");
		labelHeader.setContentMode(3);
		gridBase.addComponent(labelHeader);
		
		return gridBase;
	}

}
