package org.crsystems.crbooks.ui.windows;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class ViewAllBooks extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panelTabla;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Table tableLibros;
	@AutoGenerated
	private Label labelTittle;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ViewAllBooks() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panelTabla
		panelTabla = buildPanelTabla();
		mainLayout.addComponent(panelTabla);
		mainLayout.setComponentAlignment(panelTabla, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanelTabla() {
		// common part: create layout
		panelTabla = new Panel();
		panelTabla.setImmediate(false);
		panelTabla.setWidth("-1px");
		panelTabla.setHeight("-1px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panelTabla.setContent(verticalLayout_1);
		
		return panelTabla;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		
		// labelTittle
		labelTittle = new Label();
		labelTittle.setImmediate(false);
		labelTittle.setWidth("-1px");
		labelTittle.setHeight("-1px");
		labelTittle.setValue("<h2>Libros del Catalogo<h2>");
		labelTittle.setContentMode(3);
		verticalLayout_1.addComponent(labelTittle);
		
		// tableLibros
		tableLibros = new Table();
		tableLibros.setImmediate(false);
		tableLibros.setWidth("-1px");
		tableLibros.setHeight("-1px");
		verticalLayout_1.addComponent(tableLibros);
		verticalLayout_1.setComponentAlignment(tableLibros, new Alignment(48));
		
		return verticalLayout_1;
	}
	
	
	

}
