package org.crsystems.crbooks.models;

import java.util.List;
import java.util.Map;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import com.vaadin.annotations.AutoGenerated;

@Entity
@Table(name="Publishers")
public class Publisher extends ModelBase<Publisher, Integer> {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(updatable = false, nullable = false)
	private Integer publisherID;
	
	@Basic
	private String name;
	
	@Basic
	private String description;
	
	@Override
	public String getTableName() {
		return "Publishers";
	}

	@Override
	public boolean isValid() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Map<String, String> getErrorFields() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<Book> getBooks() {
		return Book.getByPublisher(this);
	}

	public void setBooks(List<Book> books) {
		for (Book book : books) {
			book.setPublisher(this);
		}
	}

	public static List<Publisher> getAll() {
		return ModelBase.getAll(Publisher.class, Integer.class, "Publisher");
	}

	public Integer getPublisherID() {
		return publisherID;
	}

	public void setPublisherID(Integer publisherID) {
		this.publisherID = publisherID;
	}

	public static Publisher getByID(Integer key) {
		return ModelBase.getByID(Publisher.class, Integer.class, key);
	}

}
